"""empty message

Revision ID: 00883b06b2ff
Revises: 
Create Date: 2022-12-13 02:14:51.842424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00883b06b2ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days_of_the_week', sa.String(length=120), nullable=False),
    sa.Column('breakfast', sa.String(length=80), nullable=True),
    sa.Column('lunch', sa.String(length=80), nullable=True),
    sa.Column('dinner', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days_of_the_week', sa.String(length=120), nullable=False),
    sa.Column('healthyfat', sa.String(length=80), nullable=True),
    sa.Column('protein', sa.String(length=80), nullable=True),
    sa.Column('dairy', sa.String(length=80), nullable=True),
    sa.Column('grainscarbohydrates', sa.String(length=80), nullable=True),
    sa.Column('vegetables', sa.String(length=80), nullable=True),
    sa.Column('fruits', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('meal_shop')
    op.drop_table('meal_planner')
    # ### end Alembic commands ###
