"""empty message

Revision ID: 471cac0bbdde
Revises: 62fa01b3b2e2
Create Date: 2022-12-08 00:24:18.218655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471cac0bbdde'
down_revision = '62fa01b3b2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days_of_the_week', sa.String(length=120), nullable=False),
    sa.Column('healthyfat', sa.String(length=80), nullable=True),
    sa.Column('protein', sa.String(length=80), nullable=True),
    sa.Column('dairy', sa.String(length=80), nullable=True),
    sa.Column('grainscarbohydrates', sa.String(length=80), nullable=True),
    sa.Column('vegetables', sa.String(length=80), nullable=True),
    sa.Column('fruits', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_shop')
    # ### end Alembic commands ###
