"""empty message

Revision ID: 62fa01b3b2e2
Revises: f382906f5ad0
Create Date: 2022-12-08 00:05:11.881781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fa01b3b2e2'
down_revision = 'f382906f5ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meal_planner_days_of_the_week_key', 'meal_planner', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('meal_planner_days_of_the_week_key', 'meal_planner', ['days_of_the_week'])
    # ### end Alembic commands ###
