"""empty message

Revision ID: f382906f5ad0
Revises: 57bb3bd8eaf0
Create Date: 2022-12-02 15:28:01.179689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f382906f5ad0'
down_revision = '57bb3bd8eaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days_of_the_week', sa.String(length=120), nullable=False),
    sa.Column('breakfast', sa.String(length=80), nullable=True),
    sa.Column('lunch', sa.String(length=80), nullable=True),
    sa.Column('dinner', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('days_of_the_week')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_planner')
    # ### end Alembic commands ###
